
modalities: ["rna", "mri"]
defaults: 
  - rna_model: rna_mae
  - mri_model: mri_mae_model

hidden_size: 256
is_projection: False
attention_probs_dropout_prob: 0.0
decoder_hidden_size: 128
decoder_intermediate_size: 512
decoder_num_attention_heads: 4
decoder_num_hidden_layers: 2
hidden_act: "gelu"
hidden_dropout_prob: 0.0
initializer_range: 0.02
intermediate_size: 1024
layer_norm_eps: 1e-12
mask_ratio: 0.5
model_type: "vit_mae"
norm_pix_loss: false
num_attention_heads: 4
num_channels: 1
num_hidden_layers: 4
qkv_bias: true
patch_size: 256
is_load_pretrained: false
pretrained_model_name: ""
pretrained_model_path: ""
output_dim: 20