attention_probs_dropout_prob: 0.0
decoder_hidden_size: 128
decoder_intermediate_size: 512
decoder_num_attention_heads: 4
decoder_num_hidden_layers: 2
hidden_act: "gelu"
hidden_dropout_prob: 0.0
hidden_size: 256 # maybe 384?
size: 24576
initializer_range: 0.02
intermediate_size: 1024
layer_norm_eps: 1e-12
mask_ratio: 0.0
model_type: "vit_mae"
norm_pix_loss: false
num_attention_heads: 4
num_channels: 1
num_hidden_layers: 6
patch_size: 1024
qkv_bias: true
is_load_pretrained: false
pretrained_model_name: "dna_without_clusters_mae_survival"
pretrained_model_path: ""
output_dim: 20